version: '3'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    env_file: .env
    restart: always
    ports:
      - "3307:3306"

  tpay:
    build: tpay
    volumes:
      - ./tpay:/app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: "python manage.py runserver 0.0.0.0:8080 --settings=config.settings.develop"

