version: '3'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    env_file: .env
    restart: always

  tpay:
    build: tpay
    volumes:
      - ./tpay:/app
    env_file: .env
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - "8000:8000"
    environment:
      UWSGI_HOST: tpay
    volumes:
      - ./tpay/static:/tpay_static
      - ./tpay/media:/tpay_media
    depends_on:
      - tpay
